# Generated by Django 5.0.6 on 2024-12-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmediafeedback",
            old_name="platform",
            new_name="langue",
        ),
    ]
